#! /bin/bash

if [[ $PWD != *"/glang/frontend" ]]; then
	echo "ERROR: Please run this script from glang/frontend directory."
	exit 65
fi

if [ $# -ne 2 ]; then
	echo "Usage: $0 <gramola_src_prog> <java_target_class_name>"
	exit 65
fi

SOURCE=$1
JTARGET=$2
TARGET_DIR=../src
BIN_DIR=../bin
CLASSPATH=../lib/*:.

if [ ! -d ../bin ]; then
	mkdir ../bin
fi

if [ ! -e ../lib/gramola.jar ]; then
	echo "ERROR: Could not find gramola.jar."
	exit 1
fi

rm -f $TARGET_DIR/*.java
python codegen.py $SOURCE $JTARGET

if [ $? != 0 ]; then
    echo "ERROR: code generation fails."
    exit 1
fi

mv *.java $TARGET_DIR

rm -f $BIN_DIR/*.class

javac -cp $CLASSPATH ${TARGET_DIR}/*.java

if [ $? != 0 ]; then
    echo "ERROR: Java compilation fails."
    exit 1
fi

mv ${TARGET_DIR}/*.class $BIN_DIR
