#! /bin/bash

if [[ $PWD != *"/glang/frontend" ]]; then
	echo "ERROR: Please run this script from glang/frontend directory."
	exit 65
fi

if [ $# -ne 1 ]; then
	echo "Usage: $0 <java_class_name>"
	exit 65
fi

TARGET=$1
TARGET_CLASS=../bin/$TARGET.class
CLASSPATH=../lib/*:.

if [ ! -e $TARGET_CLASS ]; then
	echo "ERROR: Could not find $TARGET in bin."
	exit 1
fi

cd ../bin

java -cp $CLASSPATH $TARGET
