# TEST: Type conversion

class MyClass():
    int i
    float f

    def MyClass __init__(int i, float f):
        self.i = i
        self.f = f

    def int get_i():
        return i

    def float get_f():
        return f

class ChildClass(MyClass):
    def ChildClass __init__(int i, float f):
        MyClass(i,f)
        self.i = i
        self.f = f


def void main():
    int i = 1
    float f = 3.14

    int a = (int) f
    
    MyClass c = ChildClass(i, f)
    ChildClass child = ChildClass(i, f)
    MyClass parent = child

#    ChildClass t = (MyClass)c # this should fail

