# Class inheritance

class MyClass():
    int i
    float f

    def void __init__(int i, float f):
        self.i = i
        self.f = f

    def int get_i():
        return i

    def float get_f():
        return f

class ChildClass(MyClass):
    def void __init__(int i, float f):
        self.i = i
        self.f = f


def void main():
    int i = 1
    float f = 3.14
    
    ChildClass c = ChildClass(i, f)

    print c.get_i()
    print c.get_f()
