# TEST: Graph operations.

def void main():
    Graph g = Graph()
	print g.get_id()

    Node n1 = g.node({"name": "Rosebud", "age": "42"})
	Node n2 = Node({"name": "Citizen Kane", "age": "72"})
	g.add_node(n2)

	Edge e1 = g.edge(n1, n2, {"relation": "is plot device in"})
	Edge e2 = Edge(n2, n1, {"relation": "has plot device named"})
	g.add_edge(e2)

    Node n3 = g.node({"name": "Rosebud", "age": "42_2"})
	print g.get_node("name", "Rosebud").get_attribute_dict()

	for Node n in g.get_nodes("name", "Rosebud"):
		print n.get_attribute_dict()

	print g.get_node_by_id(n2.get_id()).get_attribute_dict()

	for Node n in g.get_all_nodes():
		print n.get_attribute_dict()

	for Edge e in g.get_all_edges():
		print e.get_attribute_dict()
